### ISSUE TITLE
Pi5 with Companion v3.5.0+7596-main-85bb98a6 dont starts as user 'companion'

### ISSUE THREAD

**Issue by cx-networks-gmbh** [bitfocus/companion-pi#32]
# Description of the Situation

We are running companion on a raspberry pi5 with a raspbian image and companion can not start.

```
pi@CompanionPi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

After the install script the service did not start.
```
pi@CompanionPi:~ $ sudo systemctl -l status companion
× companion.service - Bitfocus Companion
     Loaded: loaded (/etc/systemd/system/companion.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-11-30 19:01:40 GMT; 54s ago
   Duration: 687ms
    Process: 1117 ExecStart=/usr/local/src/companionpi/launch.sh (code=exited, status=1/FAILURE)
   Main PID: 1117 (code=exited, status=1/FAILURE)
        CPU: 729ms

Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at /opt/companion/main.js:2:3163305
Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at f._chainOrCall (/opt/companion/main.js:2:3164520)
Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at f._dispatchSubcommand (/opt/companion/main.js:2:3163250)
Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at f._parseCommand (/opt/companion/main.js:2:3165435)
Nov 30 19:01:40 CompanionPi launch.sh[1118]: Node.js v22.11.0
Nov 30 19:01:40 CompanionPi systemd[1]: companion.service: Scheduled restart job, restart counter is at 5.
Nov 30 19:01:40 CompanionPi systemd[1]: Stopped companion.service - Bitfocus Companion.
Nov 30 19:01:40 CompanionPi systemd[1]: companion.service: Start request repeated too quickly.
Nov 30 19:01:40 CompanionPi systemd[1]: companion.service: Failed with result 'exit-code'.
Nov 30 19:01:40 CompanionPi systemd[1]: Failed to start companion.service - Bitfocus Companion.
```
And the journal logs:
```
pi@CompanionPi:~ $ journalctl -f
Nov 30 19:01:40 CompanionPi launch.sh[1118]: Error: Missing machineId
Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at new L (/opt/companion/main.js:2:3766445)
Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at f.<anonymous> (/opt/companion/main.js:2:3981805)
Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at f._actionHandler (/opt/companion/main.js:2:3156463)
Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at /opt/companion/main.js:2:3165945
Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at f._chainOrCall (/opt/companion/main.js:2:3164520)
Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at f._parseCommand (/opt/companion/main.js:2:3165920)
Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at /opt/companion/main.js:2:3163305
Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at f._chainOrCall (/opt/companion/main.js:2:3164520)
Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at f._dispatchSubcommand (/opt/companion/main.js:2:3163250)
Nov 30 19:01:40 CompanionPi launch.sh[1118]:     at f._parseCommand (/opt/companion/main.js:2:3165435)
Nov 30 19:01:40 CompanionPi launch.sh[1118]: Node.js v22.11.0
Nov 30 19:01:40 CompanionPi systemd[1]: companion.service: Scheduled restart job, restart counter is at 5.
Nov 30 19:01:40 CompanionPi systemd[1]: Stopped companion.service - Bitfocus Companion.
Nov 30 19:01:40 CompanionPi systemd[1]: companion.service: Start request repeated too quickly.
Nov 30 19:01:40 CompanionPi systemd[1]: companion.service: Failed with result 'exit-code'.
Nov 30 19:01:40 CompanionPi systemd[1]: Failed to start companion.service - Bitfocus Companion.
```

After some digging and try and error I have the feelding that the companion user can't read the machine-id of the os.
Because running companion as the user `pi` runs with no problem.
Either directly from the command line:
```
pi@CompanionPi:~ $ /usr/local/src/companionpi/launch.sh
2024-11-30T19:04:43.400Z info Main Application starting
2024-11-30T19:04:43.402Z info Registry Build 3.5.0+7596-main-85bb98a6
2024-11-30T19:04:43.403Z info Registry configuration directory: /home/pi/.config/companion-nodejs/v3.5
2024-11-30T19:04:43.444Z info Log/Controller Sentry error reporting configured
2024-11-30T19:04:43.471Z info Graphics/Controller Render worker created
2024-11-30T19:04:43.476Z info Graphics/Controller Render worker created
2024-11-30T19:04:43.478Z info Graphics/Controller Loading fonts
2024-11-30T19:04:43.492Z info Graphics/Controller Fonts loaded
2024-11-30T19:04:43.525Z info Service/BonjourDiscovery Listening for Bonjour messages
2024-11-30T19:04:43.639Z info Graphics/Controller Render worker created
2024-11-30T19:04:43.641Z info Graphics/Controller Render worker created
2024-11-30T19:04:43.643Z info Graphics/Controller Render worker created
2024-11-30T19:04:43.645Z info Graphics/Controller Render worker created
2024-11-30T19:04:44.076Z info Instance/Modules Looking for extra modules in: /opt/companion-module-dev
2024-11-30T19:04:44.079Z info Instance/Modules Found 0 extra modules
Started
2024-11-30T19:04:44.144Z info UI/Server new url: http://0.0.0.0:8000/
```

Or if we change the user in the service:
```
[Unit]
Description=Bitfocus Companion
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=pi
Environment=COMPANION_IN_SYSTEMD=1
ExecStart=/usr/local/src/companionpi/launch.sh
Restart=on-failure
KillSignal=SIGINT
TimeoutStopSec=60

[Install]
WantedBy=multi-user.target
```

# Expected behaviour
After install the service should run just fine.

# What we tried
- Regenerated the machine-id: `rm -f /etc/machine-id /var/lib/dbus/machine-id && dbus-uuidgen --ensure=/etc/machine-id && dbus-uuidgen --ensure`
- Reinstalled companion. Removed the companion user prior to reinstall

**Comment by Julusian** [comment]
Could you check the permissions and contents of the `/home/companion/.config/companion-nodejs/machid`?

It looks like the permissions for that file have gotten messed up causing it to fail to read the value from it (or perhaps it is empty?) and our handling of these scenarios are not very good

**Comment by cx-networks-gmbh** [comment]
I checked the permissons:
```
pi@CompanionPi:~ $ sudo ls -la /home/companion/.config/companion-nodejs/machid
 -rw-r--r-- 1 companion companion 0 Oct 10 18:41 /home/companion/.config/companion-nodejs/machid
```

And the `machid` file is empty:
```
cat /home/companion/.config/companion-nodejs/machid
```

**Comment by Julusian** [comment]
Permissions look ok, but the file shouldn't be empty.
Remove it and it will get recreated and it should launch ok

**Comment by cx-networks-gmbh** [comment]
Yes! Removing the file and a reboot did the trick! Thank you!
`pi@CompanionPi:~ $ sudo rm -f /home/companion/.config/companion-nodejs/machid`

**Comment by cx-networks-gmbh** [comment]
I have to reopen this issue. With a fresh image downloaded from the companion website and freshly flashed to SD-Card, companion can not start. With the same issue, the `machid` file is empty and resolving in companion not able to start.

Removing the `machid` file did not regenerate it with any content.

Even worse, while removing the file and reboot, the pi can not boot anymore. It boots until the login prompt appears and then crashes and turns off. Until now I am not able to get some proper logs for the crash.

**Comment by Julusian** [comment]
I've just written the latest pi image `companion-pi-beta-265-29-12-24.img` to an sd card and run it on my pi5, and havent encountered the issues you have.

I've tried deleting the machid file and restarting companion or the pi, and updating companion. 

Are you able to try using a different sd or brand of sd card?
It feels like it could be experiencing corruption when writing files to disk, causing that file to be empty for you or worse causing it to not boot. I can't think what companion could possibly do to the system to cause it to not boot, companion doesn't have root permissions so it can't go modifying any system files/binaries/settings/whatever.

**Comment by cx-networks-gmbh** [comment]
I have spent some time trying and digging into this. Flashed another SD card (Sandisk Ultra 32gb), same problem. Tried an NVMe SSD with an ssd head, same problem and sometimes not booting at all. The fact that the Pi didn't boot at all a few times made me worry about the power supply. So tried a different power supply and that worked fine. My power supply had too little power for proper operation. Strangely enough, the symptoms of the problem were the same as the original problem.

So closing this again. Thanks @Julusian for your help!
